### ISSUE TITLE
支持局域网语音聊天吗?

### ISSUE THREAD

**Issue by RainStone1988** [ThePupilOfTheOcean/TencentVoiceForUE4#2]
(｡･∀･)ﾉﾞ嗨, 很高兴看到腾讯云语音的UE4插件! 感谢工作!
我想知道, 目前该插件支持局域网语音聊天吗>> :-)

**Comment by luochuanyuewu** [comment]
你需要有一个腾讯云后台app key。然后无论你是同一个局域网的电脑还是不同地方的电脑。只要能连接互联网。都能语音通话。

**Comment by ThePupilOfTheOcean** [comment]
@luochuanyuewu 如他所说。我们只是使用了腾讯云语音服务。所以如果您也想使用，您需要去新建语音服务，这里是[地址](https://cloud.tencent.com/document/product/556/7474)。然后使用您自己申请的App ID和App Key，就可以使用语音功能了。另外我更新了README.md，您按照步骤来，应该就可以正常使用了。
